import './globals.css';

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: 'Woman Protection Dashboard',
    description: 'Generated by @Mello',
};

export default function RootLayout({
    children, // will be a page or nested layout
}: {
    children: React.ReactNode;
}) {
    return (
        <html>
            <body className={`${inter.className}`}>
                {/* Include shared UI here e.g. a header or sidebar */}
                {children}
            </body>
        </html>
    );
}